# Generated by Django 5.1.1 on 2024-09-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=2, null=True)),
                ('image', models.BooleanField(default=0)),
                ('picture', models.ImageField(default='default.jpg', upload_to='team_images')),
                ('instagramUser', models.CharField(blank=True, default=None, max_length=255)),
                ('xUser', models.CharField(blank=True, default=None, max_length=255)),
                ('slug', models.SlugField(blank=True, default='')),
                ('positions', models.ManyToManyField(to='main.positions')),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
    ]
