# Generated by Django 5.1.1 on 2024-09-08 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positions',
            options={'ordering': ['position'], 'verbose_name_plural': 'Positions'},
        ),
        migrations.AddField(
            model_name='teams',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 12, 21, 40, 40465)),
        ),
    ]
