# Generated by Django 5.1.1 on 2024-09-08 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_positions_options_teams_dateadded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, default=None, max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['post'],
            },
        ),
        migrations.RemoveField(
            model_name='teams',
            name='positions',
        ),
        migrations.AlterField(
            model_name='teams',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 12, 39, 37, 94997)),
        ),
        migrations.AddField(
            model_name='teams',
            name='posts',
            field=models.ManyToManyField(to='main.posts'),
        ),
    ]
