# Generated by Django 5.1.1 on 2024-09-09 02:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_posts_remove_teams_positions_alter_teams_dateadded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agegroups', models.CharField(blank=True, default=None, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'agegroups',
                'ordering': ['agegroups'],
            },
        ),
        migrations.CreateModel(
            name='TeamTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(blank=True, default=None, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Team Types',
                'ordering': ['types'],
            },
        ),
        migrations.AddField(
            model_name='teams',
            name='contactEmail',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='contactName',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='contactPhone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 22, 9, 57, 466792)),
        ),
        migrations.AddField(
            model_name='teams',
            name='agegroups',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.agegroups'),
        ),
        migrations.AddField(
            model_name='teams',
            name='teamTypes',
            field=models.ManyToManyField(to='main.teamtypes'),
        ),
    ]
