# Generated by Django 5.1.1 on 2024-09-09 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_teams_dateadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='agegroups',
        ),
        migrations.AlterField(
            model_name='teams',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 17, 57, 56, 175539)),
        ),
        migrations.AddField(
            model_name='teams',
            name='agegroups',
            field=models.ManyToManyField(to='main.agegroups'),
        ),
    ]
