# Generated by Django 5.1.1 on 2024-09-09 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_teams_agegroups_alter_teams_dateadded_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agegroups',
            options={'ordering': ['name'], 'verbose_name_plural': 'agegroups'},
        ),
        migrations.RenameField(
            model_name='agegroups',
            old_name='agegroups',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='teams',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 18, 11, 15, 7430)),
        ),
    ]
