# Generated by Django 5.1.1 on 2024-09-10 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_agegroups_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='agegroups',
            field=models.ManyToManyField(blank=True, to='main.agegroups'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 20, 56, 22, 654941)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='posts',
            field=models.ManyToManyField(blank=True, to='main.posts'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='teamTypes',
            field=models.ManyToManyField(blank=True, to='main.teamtypes'),
        ),
    ]
