# Generated by Django 5.1.1 on 2024-09-10 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_teams_agegroups_alter_teams_dateadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 17, 21, 19, 58976)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='instagramUser',
            field=models.CharField(blank=True, default='instagram.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='teams',
            name='xUser',
            field=models.CharField(blank=True, default='x.com', max_length=255),
        ),
    ]
