# Generated by Django 5.1.1 on 2024-10-05 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_teams_description_alter_teams_dateadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='image',
        ),
        migrations.AlterField(
            model_name='teams',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 17, 41, 47, 502402)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='static/images/teams'),
        ),
    ]
