# Generated by Django 5.1.1 on 2024-10-05 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_teams_image_alter_teams_dateadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 17, 47, 24, 101036)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='collectedstatic/images/teams'),
        ),
    ]
