# Generated by Django 5.1.1 on 2024-10-06 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_teams_dateadded_alter_teams_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 19, 8, 25, 551857)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='images/teams'),
        ),
    ]
