# Generated by Django 5.1.1 on 2024-10-08 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_teams_dateadded_alter_teams_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 11, 6, 44, 998726)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='picture',
            field=models.ImageField(default='images/teams/default.png', upload_to='images/teams'),
        ),
    ]
