# Generated by Django 5.1.1 on 2024-10-14 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_teams_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='lookingforplayers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 18, 9, 25, 878322)),
        ),
    ]
