# Generated by Django 5.1.1 on 2024-10-20 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_teams_lookingforplayers_alter_teams_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 15, 13, 58, 160470)),
        ),
    ]
